---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
##install.packages("rvest")
library(rvest) 
for (n in 2001:2005){
PttTechJob<-paste0("https://www.ptt.cc/bbs/Tech_Job/index",n,".html")
PttContent<-read_html(PttTechJob)
post_Title <- PttContent %>% html_nodes(".title") %>% html_text()
post_PushNum<-PttContent %>% html_nodes(".nrec") %>% html_text()
post_Author<-PttContent %>% html_nodes(".author") %>% html_text()


if(n==2001){
  PttTechJob_posts1 <- data.frame(Title = post_Title,PushNum = post_PushNum,Author=post_Author)
}else if(n==2002){
  PttTechJob_posts2 <- data.frame(Title = post_Title,PushNum = post_PushNum,Author=post_Author)
}else if(n==2003){
  PttTechJob_posts3 <- data.frame(Title = post_Title,PushNum = post_PushNum,Author=post_Author)
}else if(n==2004){
  PttTechJob_posts4 <- data.frame(Title = post_Title,PushNum = post_PushNum,Author=post_Author)
}else if(n==2005){
  PttTechJob_posts5 <- data.frame(Title = post_Title,PushNum = post_PushNum,Author=post_Author)
   PttTechJob_posts <- rbind(PttTechJob_posts1,PttTechJob_posts2,PttTechJob_posts3,PttTechJob_posts4,PttTechJob_posts5)
}
}
```

## 爬蟲結果呈現
```{r}
knitr::kable(
    PttTechJob_posts[1:100,c("Title","PushNum","Author")])

```

## 解釋爬蟲結果 
```{r}
str(PttTechJob_posts)
```

可透過str(PttTechJob)的結果中「100 obs. of  3 variables」可得知總共爬出100篇文章之標題。

```{r}
table(PttTechJob_posts$Author)
```

可透過table(PttTechJob_posts$Author)的結果中可看出每個作者的文章數，其中「lvprada」為三篇，是本爬蟲結果中最多者。

從爬蟲網頁後這一百個標題中，可以看出有七成是【請益】，可以看出科技業的人們喜歡在板上尋求公司的資訊，尋求到最好的待遇，而剩下的三成中，可分成三類：【討論】、【徵才】、【新聞】，讓板上使用者可以吸收一些新知及即時訊息！
